Repository kobsio/kobs, pull requests merged in 2022-09, with the labels that each got.

#424 [app] Update Dependencies
  .github/workflows/codeql.yaml
  .github/workflows/continuous-integration.yaml
  CONTRIBUTING.md
  cmd/kobs/Dockerfile
  docs/contributing/use-custom-plugins.md
  go.mod
  go.sum
  package.json
  plugins/app/package.json
  plugins/plugin-azure/package.json
  plugins/plugin-elasticsearch/package.json
  plugins/plugin-flux/package.json
  plugins/plugin-github/package.json
  plugins/plugin-grafana/package.json
  plugins/plugin-harbor/package.json
  plugins/plugin-helm/package.json
  plugins/plugin-istio/package.json
  plugins/plugin-jaeger/package.json
  plugins/plugin-jira/package.json
  plugins/plugin-kiali/package.json
  plugins/plugin-klogs/package.json
  plugins/plugin-opsgenie/package.json
  plugins/plugin-prometheus/package.json
  plugins/plugin-rss/package.json
  plugins/plugin-signalsciences/package.json
  plugins/plugin-sonarqube/package.json
  plugins/plugin-sql/package.json
  plugins/plugin-techdocs/package.json
  yarn.lock
Labels: changelog: changed

#429 [jaeger] Add Panels for Service Performance Monitoring
  docs/plugins/assets/jaeger-service-performance-monitoring.png
  docs/plugins/azure.md
  docs/plugins/jaeger.md
  plugins/plugin-jaeger/cmd/jaeger.go
  plugins/plugin-jaeger/pkg/instance/instance.go
  plugins/plugin-jaeger/pkg/instance/instance_mock.go
  plugins/plugin-jaeger/src/components/page/Monitor.tsx
  plugins/plugin-jaeger/src/components/page/MonitorToolbar.tsx
  plugins/plugin-jaeger/src/components/page/MonitorToolbarSpanKinds.tsx
  plugins/plugin-jaeger/src/components/panel/MonitorOperations.tsx
  plugins/plugin-jaeger/src/components/panel/MonitorServiceCalls.tsx
  plugins/plugin-jaeger/src/components/panel/MonitorServiceErrors.tsx
  plugins/plugin-jaeger/src/components/panel/MonitorServiceLatency.tsx
  plugins/plugin-jaeger/src/components/panel/Panel.tsx
  plugins/plugin-jaeger/src/utils/helpers.ts
  plugins/plugin-jaeger/src/utils/interfaces.ts
Labels: changelog: added

#432 Add topologySpreadConstraints value in Helm chart
  deploy/helm/hub/Chart.yaml
  deploy/helm/hub/templates/deployment.yaml
  deploy/helm/hub/values.yaml
  deploy/helm/satellite/Chart.yaml
  deploy/helm/satellite/templates/deployment.yaml
  deploy/helm/satellite/values.yaml
  docs/getting-started/installation/helm.md
Labels: changelog: added

#431 [mongodb] Add MongoDB Plugin
  cmd/kobs/main.go
  docs/plugins/helm.md
  docs/plugins/mongodb.md
  mkdocs.yml
  package.json
  plugins/plugin-mongodb/cmd/mongodb.go
  plugins/plugin-mongodb/package.json
  plugins/plugin-mongodb/pkg/instance/instance.go
  plugins/plugin-mongodb/pkg/instance/structs.go
  plugins/plugin-mongodb/public/index.html
  plugins/plugin-mongodb/src/App.tsx
  plugins/plugin-mongodb/src/assets/finddocument.css
  plugins/plugin-mongodb/src/assets/icon.png
  plugins/plugin-mongodb/src/components/instance/Instance.tsx
  plugins/plugin-mongodb/src/components/page/BsonInput.tsx
  plugins/plugin-mongodb/src/components/page/BsonPreview.tsx
  plugins/plugin-mongodb/src/components/page/DocumentPage.tsx
  plugins/plugin-mongodb/src/components/page/OverviewPage.tsx
  plugins/plugin-mongodb/src/components/page/Page.tsx
  plugins/plugin-mongodb/src/components/page/QueryPage.tsx
  plugins/plugin-mongodb/src/components/page/QueryPageToolbar.tsx
  plugins/plugin-mongodb/src/components/panel/Collection.tsx
  plugins/plugin-mongodb/src/components/panel/CollectionDetails.tsx
  plugins/plugin-mongodb/src/components/panel/Collections.tsx
  plugins/plugin-mongodb/src/components/panel/Count.tsx
  plugins/plugin-mongodb/src/components/panel/DBStats.tsx
  plugins/plugin-mongodb/src/components/panel/Find.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocument.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocumentDetails.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocumentDetailsTree.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocuments.tsx
  plugins/plugin-mongodb/src/components/panel/Panel.tsx
  plugins/plugin-mongodb/src/index.tsx
  plugins/plugin-mongodb/src/react-app-env.d.ts
  plugins/plugin-mongodb/src/setupModuleFederation.js
  plugins/plugin-mongodb/src/setupTests.ts
  plugins/plugin-mongodb/src/utils/constants.ts
  plugins/plugin-mongodb/src/utils/helpers.ts
  plugins/plugin-mongodb/src/utils/interfaces.ts
  plugins/plugin-mongodb/src/utils/mongo-completions.ts
  plugins/plugin-mongodb/tsconfig.json
  yarn.lock
Labels: changelog: added

#433 [mongodb] Fix null error and limit parameter
  plugins/plugin-mongodb/src/components/page/BsonPreview.tsx
  plugins/plugin-mongodb/src/components/page/QueryPage.tsx
  plugins/plugin-mongodb/src/components/page/QueryPageToolbar.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocument.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocumentDetails.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocumentDetailsTree.tsx
  plugins/plugin-mongodb/src/components/panel/FindDocuments.tsx
Labels: changelog: fixed
