Repository kobsio/kobs, pull requests merged in 2023-03, with the labels that each got.

#474 [core] Improve Node.js Setup
  .github/workflows/continuous-integration.yaml
  app/package.json
  app/packages/app/package.json
  app/packages/core/package.json
  cmd/kobs/Dockerfile
Labels: changelog: changed

#473 [core] Add Panels for Applications, Teams and Dashboards
  app/packages/core/src/components/applications/Application.tsx
  app/packages/core/src/components/applications/ApplicationGroupsPanel.tsx
  app/packages/core/src/components/applications/ApplicationsPage.tsx
  app/packages/core/src/components/applications/ApplicationsPanel.tsx
  app/packages/core/src/components/applications/Topology.tsx
  app/packages/core/src/components/applications/TopologyPage.tsx
  app/packages/core/src/components/applications/TopologyPanel.tsx
  app/packages/core/src/components/dashboards/Dashboards.tsx
  app/packages/core/src/components/dashboards/DashboardsPanel.tsx
  app/packages/core/src/components/plugins/PluginPanel.test.tsx
  app/packages/core/src/components/plugins/PluginPanel.tsx
  app/packages/core/src/components/plugins/PluginsPage.tsx
  app/packages/core/src/components/teams/Teams.tsx
  app/packages/core/src/components/teams/TeamsPage.tsx
  app/packages/core/src/components/teams/TeamsPanel.tsx
  app/packages/core/src/components/utils/Pagination.tsx
  app/packages/core/src/components/utils/PluginPanel.test.tsx
  app/packages/core/src/components/utils/PluginPanel.tsx
  app/packages/core/src/context/GridContext.tsx
  app/packages/core/src/context/PluginContext.tsx
  app/packages/core/src/crds/dashboard.ts
  app/packages/core/src/index.ts
  deploy/helm/satellite/crds/kobs.io_applications.yaml
  deploy/helm/satellite/crds/kobs.io_dashboards.yaml
  deploy/helm/satellite/crds/kobs.io_teams.yaml
  deploy/helm/satellite/crds/kobs.io_users.yaml
  deploy/kustomize/crds/kobs.io_applications.yaml
  deploy/kustomize/crds/kobs.io_dashboards.yaml
  deploy/kustomize/crds/kobs.io_teams.yaml
  deploy/kustomize/crds/kobs.io_users.yaml
  pkg/cluster/kubernetes/apis/dashboard/v1/types.go
  pkg/hub/api/applications/applications.go
  pkg/hub/api/applications/applications_test.go
  pkg/hub/api/applications/topology.go
  pkg/hub/api/applications/topology_test.go
  pkg/hub/db/db.go
  pkg/hub/db/db_mock.go
  pkg/hub/db/db_test.go
  pkg/hub/db/types.go
Labels: changelog: changed

#475 [core] Show / Hide Rows in Dashboard based on Condition
  app/packages/core/src/components/dashboards/Dashboards.tsx
  app/packages/core/src/crds/dashboard.ts
  deploy/helm/satellite/crds/kobs.io_applications.yaml
  deploy/helm/satellite/crds/kobs.io_dashboards.yaml
  deploy/helm/satellite/crds/kobs.io_teams.yaml
  deploy/helm/satellite/crds/kobs.io_users.yaml
  deploy/kustomize/crds/kobs.io_applications.yaml
  deploy/kustomize/crds/kobs.io_dashboards.yaml
  deploy/kustomize/crds/kobs.io_teams.yaml
  deploy/kustomize/crds/kobs.io_users.yaml
  pkg/cluster/kubernetes/apis/dashboard/v1/types.go
Labels: changelog: added

#476 [core] Fix Exports for Components
  app/packages/core/src/components/app/App.tsx
  app/packages/core/src/components/app/Home.tsx
  app/packages/core/src/components/app/signin/Signin.test.tsx
  app/packages/core/src/components/app/signin/SigninOIDCCallback.test.tsx
  app/packages/core/src/components/applications/ApplicationGroupsPanel.tsx
  app/packages/core/src/components/applications/ApplicationPage.tsx
  app/packages/core/src/components/applications/ApplicationsInsights.tsx
  app/packages/core/src/components/applications/ApplicationsPage.test.tsx
  app/packages/core/src/components/applications/ApplicationsPage.tsx
  app/packages/core/src/components/applications/ApplicationsPanel.tsx
  app/packages/core/src/components/applications/ApplicationsToolbar.test.tsx
  app/packages/core/src/components/applications/TopologyPage.tsx
  app/packages/core/src/components/applications/TopologyPanel.tsx
  app/packages/core/src/components/dashboards/Dashboards.tsx
  app/packages/core/src/components/dashboards/DashboardsPage.tsx
  app/packages/core/src/components/plugins/PluginsPage.test.tsx
  app/packages/core/src/components/plugins/PluginsPage.tsx
  app/packages/core/src/components/resources/ResourcesClusters.test.tsx
  app/packages/core/src/components/resources/ResourcesNamespaces.test.tsx
  app/packages/core/src/components/teams/TeamPage.tsx
  app/packages/core/src/components/teams/Teams.tsx
  app/packages/core/src/components/teams/TeamsPage.tsx
  app/packages/core/src/components/utils/DetailsDrawer.test.tsx
  app/packages/core/src/components/utils/DetailsDrawer.tsx
  app/packages/core/src/components/utils/Page.test.tsx
  app/packages/core/src/components/utils/Page.tsx
  app/packages/core/src/components/utils/Pagination.test.tsx
  app/packages/core/src/components/utils/Pagination.tsx
  app/packages/core/src/components/utils/UseQueryWrapper.test.tsx
  app/packages/core/src/components/utils/UseQueryWrapper.tsx
  app/packages/core/src/context/PluginContext.test.tsx
  app/packages/core/src/context/QueryClientProvider.tsx
  app/packages/core/src/index.ts
  app/packages/core/src/utils/hooks/useMemoizedFn.test.tsx
  app/packages/core/src/utils/hooks/useMemoizedFn.tsx
  app/packages/core/src/utils/hooks/useQueryState.test.tsx
  app/packages/core/src/utils/hooks/useQueryState.tsx
  app/packages/core/src/utils/hooks/useUpdate.test.tsx
  app/packages/core/src/utils/hooks/useUpdate.tsx
Labels: changelog: fixed

#479 [core] Small Code Improvements
  app/packages/core/src/components/app/layout/Header.tsx
  app/packages/core/src/components/app/layout/Layout.tsx
  app/packages/core/src/components/app/layout/Sidebar.tsx
  app/packages/core/src/components/app/signin/Signin.tsx
  app/packages/core/src/components/app/signin/SigninOIDC.tsx
  app/packages/core/src/components/applications/Application.tsx
  app/packages/core/src/components/applications/ApplicationGroupsPanel.tsx
  app/packages/core/src/components/applications/ApplicationsToolbar.tsx
  app/packages/core/src/components/applications/Topology.tsx
  app/packages/core/src/components/dashboards/Dashboards.tsx
  app/packages/core/src/components/plugins/PluginPage.tsx
  app/packages/core/src/components/plugins/PluginPanel.tsx
  app/packages/core/src/components/resources/ResourcesSelectClusters.tsx
  app/packages/core/src/components/resources/ResourcesSelectNamespaces.tsx
  app/packages/core/src/components/resources/ResourcesSelectResources.tsx
  app/packages/core/src/components/resources/overview/DaemonSet.tsx
  app/packages/core/src/components/resources/overview/Deployment.tsx
  app/packages/core/src/components/resources/overview/Job.tsx
  app/packages/core/src/components/resources/overview/Pod.tsx
  app/packages/core/src/components/resources/overview/Selector.tsx
  app/packages/core/src/components/resources/overview/StatefulSet.tsx
  app/packages/core/src/components/utils/Pagination.tsx
  app/packages/core/src/components/utils/PluginPanel.tsx
  app/packages/core/src/components/utils/UseQueryWrapper.tsx
  app/packages/core/src/context/APIContext.tsx
  app/packages/core/src/context/AppContext.tsx
  app/packages/core/src/context/GridContext.tsx
  app/packages/core/src/context/PluginContext.tsx
  app/packages/core/src/utils/hooks/useDimensions.tsx
  app/packages/core/src/utils/hooks/useQueryState.tsx
  docs/contributing/create-a-plugin.md
Labels: changelog: changed

#481 [core] Fix Applications and Teams
  app/packages/core/src/components/applications/ApplicationPage.tsx
  app/packages/core/src/components/applications/ApplicationsPanel.tsx
  app/packages/core/src/components/teams/TeamPage.tsx
Labels: changelog: fixed

#482 [core] Add Select All Option for Clusters
  app/packages/core/src/components/resources/ResourcesSelectClusters.test.tsx
  app/packages/core/src/components/resources/ResourcesSelectClusters.tsx
Labels: changelog: changed

#483 [core] Improve Editor Component
  .github/workflows/continuous-integration.yaml
  app/package-lock.json
  app/packages/app/package.json
  app/packages/app/src/main.tsx
  app/packages/app/vite.config.ts
  app/packages/core/package.json
  app/packages/core/src/components/plugins/PluginPanel.test.tsx
  app/packages/core/src/components/resources/ResourceDetails.tsx
  app/packages/core/src/components/resources/actions/Debug.tsx
  app/packages/core/src/components/resources/actions/Edit.tsx
  app/packages/core/src/components/utils/editor/Editor.tsx
  app/packages/core/src/components/utils/editor/monaco.tsx
  app/packages/core/src/components/utils/editor/themes.ts
  app/packages/core/src/components/utils/editor/yaml.worker.ts
  app/packages/core/vite.config.ts
Labels: changelog: fixed

#484 [core] Fix Positioning of Options Component in Toolbar
  app/packages/core/src/components/dashboards/Dashboards.tsx
  app/packages/core/src/components/utils/Options.tsx
Labels: changelog: fixed

#485 [core] Fix Font Family for Monaco
  app/packages/core/src/components/utils/editor/Editor.tsx
Labels: changelog: fixed

#488 [core] Fix OOM Kills by Disabling Source Maps
  .github/workflows/continuous-integration.yaml
  app/package-lock.json
  app/packages/app/package.json
  app/packages/app/vite.config.ts
  app/packages/core/package.json
  app/packages/core/src/components/utils/editor/monaco.tsx
  app/packages/core/vite.config.ts
  cmd/kobs/Dockerfile
Labels: changelog: fixed

#486 [core] Add ECharts and Charts Component
  app/package-lock.json
  app/packages/core/package.json
  app/packages/core/src/components/utils/charts/chart-theme.ts
  app/packages/core/src/components/utils/charts/charts.tsx
  app/packages/core/src/index.ts
Labels: changelog: added

#492 [core] Use GitHub Container Registry instead of Docker Hub
  .github/workflows/continuous-delivery.yaml
Labels: changelog: changed

#493 [helm] Adjust Helm Plugin
  .github/workflows/continuous-integration.yaml
  app/package-lock.json
  app/packages/app/src/main.tsx
  app/packages/core/src/components/utils/DescriptionList.tsx
  app/packages/helm/package.json
  app/packages/helm/src/assets/icon.png
  app/packages/helm/src/components/Editor.tsx
  app/packages/helm/src/components/HelmPage.test.tsx
  app/packages/helm/src/components/HelmPage.tsx
  app/packages/helm/src/components/HelmPanel.test.tsx
  app/packages/helm/src/components/HelmPanel.tsx
  app/packages/helm/src/components/History.tsx
  app/packages/helm/src/components/Release.tsx
  app/packages/helm/src/components/Releases.tsx
  app/packages/helm/src/index.ts
  app/packages/helm/src/setupTests.ts
  app/packages/helm/src/utils/utils.ts
  app/packages/helm/src/vite-env.d.ts
  app/packages/helm/tsconfig.json
  app/packages/helm/tsconfig.node.json
  app/packages/helm/vite.config.ts
  cmd/kobs/main.go
  go.mod
  pkg/hub/api/applications/applications.go
  pkg/plugins/harbor/harbor.go
  pkg/plugins/harbor/harbor_test.go
  pkg/plugins/harbor/router.go
  pkg/plugins/helm/client/client.go
  pkg/plugins/helm/client/client_mock.go
  pkg/plugins/helm/client/client_test.go
  pkg/plugins/helm/client/helpers.go
  pkg/plugins/helm/client/helpers_test.go
  pkg/plugins/helm/client/types.go
  pkg/plugins/helm/helm.go
  pkg/plugins/helm/helm_test.go
  pkg/plugins/helm/router.go
  pkg/plugins/helm/router_test.go
  pkg/utils/middleware/pluginproxy/pluginproxy.go
Labels: changelog: changed

#496 [sonarqube] Adjust SonarQube Plugin
  .github/workflows/continuous-integration.yaml
  app/package-lock.json
  app/packages/app/src/main.tsx
  app/packages/core/src/components/utils/PluginPanel.tsx
  app/packages/sonarqube/package.json
  app/packages/sonarqube/src/assets/icon.png
  app/packages/sonarqube/src/components/Measures.tsx
  app/packages/sonarqube/src/components/SonarQubePage.test.tsx
  app/packages/sonarqube/src/components/SonarQubePage.tsx
  app/packages/sonarqube/src/components/SonarQubePanel.test.tsx
  app/packages/sonarqube/src/components/SonarQubePanel.tsx
  app/packages/sonarqube/src/index.ts
  app/packages/sonarqube/src/setupTests.ts
  app/packages/sonarqube/src/utils/utils.ts
  app/packages/sonarqube/src/vite-env.d.ts
  app/packages/sonarqube/tsconfig.json
  app/packages/sonarqube/tsconfig.node.json
  app/packages/sonarqube/vite.config.ts
  cmd/kobs/main.go
  pkg/plugins/grafana/instance/instance_test.go
  pkg/plugins/sonarqube/instance/instance.go
  pkg/plugins/sonarqube/instance/instance_mock.go
  pkg/plugins/sonarqube/instance/instance_test.go
  pkg/plugins/sonarqube/instance/request.go
  pkg/plugins/sonarqube/instance/request_test.go
  pkg/plugins/sonarqube/instance/types.go
  pkg/plugins/sonarqube/router.go
  pkg/plugins/sonarqube/router_test.go
  pkg/plugins/sonarqube/sonarqube.go
  pkg/plugins/sonarqube/sonarqube_test.go
Labels: changelog: changed

#498 [flux] Add Panel Actions
  app/packages/flux/src/components/FluxPanel.tsx
Labels: changelog: changed

#499 [helm] Add Panel Actions
  app/packages/helm/src/components/HelmPanel.tsx
  app/packages/helm/src/components/History.tsx
  app/packages/helm/src/components/Releases.tsx
Labels: changelog: changed

#500 [harbor] Add Panel Actions
  app/packages/harbor/src/components/HarborPanel.tsx
Labels: changelog: changed

#501 [core] Fix DetailsDrawer and Replace Paper Component
  app/packages/core/src/components/app/signin/Signin.tsx
  app/packages/core/src/components/resources/Resources.tsx
  app/packages/core/src/components/utils/DetailsDrawer.tsx
Labels: changelog: changed

#503 [core] Don't Reset "perPage" Option
  app/packages/core/src/components/applications/ApplicationsToolbar.test.tsx
  app/packages/core/src/components/applications/ApplicationsToolbar.tsx
  app/packages/core/src/components/plugins/PluginsPage.tsx
  app/packages/core/src/components/teams/TeamsPage.tsx
  app/packages/sonarqube/src/components/SonarQubePage.tsx
Labels: changelog: fixed

#504 [prometheus] Add Query History
  app/packages/core/src/components/utils/editor/Editor.tsx
  app/packages/core/src/index.ts
  app/packages/core/src/setupTests.ts
  app/packages/core/src/utils/statehistory.test.ts
  app/packages/core/src/utils/statehistory.ts
  app/packages/prometheus/src/components/PrometheusPage.tsx
Labels: changelog: added

#505 [core] Add "Clear" Action to Search Fields
  app/packages/core/src/components/applications/ApplicationsToolbar.tsx
  app/packages/core/src/components/plugins/PluginsPage.tsx
  app/packages/core/src/components/teams/TeamsPage.tsx
  app/packages/core/src/utils/statehistory.ts
  app/packages/grafana/src/components/GrafanaPage.tsx
  app/packages/harbor/src/components/HarborPage.tsx
  app/packages/prometheus/src/components/PrometheusPage.tsx
  app/packages/rss/src/components/RSSPage.tsx
  app/packages/sonarqube/src/components/SonarQubePage.tsx
Labels: changelog: added

#506 [prometheus] Reduce "getStateHistory" Calls
  app/packages/prometheus/src/components/PrometheusPage.tsx
Labels: changelog: fixed

#502 [core] Persist User Selected Options
  app/packages/core/src/components/app/layout/Sidebar.tsx
  app/packages/core/src/components/app/signin/Signin.tsx
  app/packages/core/src/components/applications/ApplicationsPage.tsx
  app/packages/core/src/components/applications/TopologyPage.tsx
  app/packages/core/src/components/plugins/PluginsPage.tsx
  app/packages/core/src/components/resources/ResourcesPage.tsx
  app/packages/core/src/components/teams/TeamsPage.tsx
  app/packages/core/src/index.ts
  app/packages/core/src/utils/hooks/useLocalStorageState.test.ts
  app/packages/core/src/utils/hooks/useLocalStorageState.ts
  app/packages/core/src/utils/hooks/useQueryState.tsx
  app/packages/flux/src/components/FluxPage.tsx
  app/packages/helm/src/components/HelmPage.tsx
Labels: changelog: added

#511 [core] Fix Label Selector for Resources
  pkg/hub/api/resources/resources.go
Labels: changelog: fixed

#512 [core] Allow Plugin Mounts to Return Nil
  pkg/cluster/plugins/plugins.go
  pkg/hub/plugins/plugins.go
  pkg/plugins/harbor/harbor.go
  pkg/plugins/harbor/harbor_test.go
  pkg/plugins/harbor/router.go
  pkg/plugins/opsgenie/opsgenie.go
  pkg/plugins/opsgenie/opsgenie_test.go
  pkg/plugins/rss/router.go
  pkg/plugins/rss/router_test.go
  pkg/plugins/rss/rss.go
  pkg/plugins/rss/rss_test.go
  pkg/plugins/signalsciences/router.go
  pkg/plugins/signalsciences/router_test.go
  pkg/plugins/signalsciences/signalsciences.go
  pkg/plugins/signalsciences/signalsciences_test.go
  pkg/plugins/sonarqube/router.go
  pkg/plugins/sonarqube/router_test.go
  pkg/plugins/sonarqube/sonarqube.go
  pkg/plugins/sonarqube/sonarqube_test.go
Labels: changelog: changed

#514 [core] Fix Time Handling in "useQueryState" Hook
  app/packages/core/src/utils/hooks/useQueryState.test.tsx
  app/packages/core/src/utils/hooks/useQueryState.tsx
  app/packages/core/src/utils/times.ts
Labels: changelog: fixed

#515 [core] Improve Padding for Plugin Panels
  app/packages/core/src/components/applications/ApplicationGroupsPanel.tsx
  app/packages/core/src/components/utils/PluginPanel.tsx
  app/packages/prometheus/src/components/PrometheusPanel.tsx
Labels: changelog: fixed

#518 [prometheus] Add Sorting for Tables
  app/packages/prometheus/src/components/Chart.tsx
  app/packages/prometheus/src/components/PrometheusPanel.tsx
Labels: changelog: added

#517 Prometheus use ChartTooltip Component
  app/packages/prometheus/src/components/Chart.tsx
  app/packages/prometheus/src/components/Legend.tsx
  app/packages/prometheus/src/components/PrometheusPage.test.tsx
  app/packages/prometheus/src/components/PrometheusPage.tsx
  app/packages/prometheus/src/components/PrometheusPanel.test.tsx
  app/packages/prometheus/src/components/PrometheusPanel.tsx
  app/packages/prometheus/src/utils/utils.ts
  pkg/plugins/prometheus/instance/instance.go
  pkg/plugins/prometheus/instance/types.go
Labels: changelog: changed

#521 [kiali] Fix package.json
  app/package-lock.json
  app/packages/kiali/package.json
Labels: changelog: fixed

#522 [jaeger] Add Flamegraph
  app/package-lock.json
  app/packages/app/src/main.tsx
  app/packages/jaeger/package.json
  app/packages/jaeger/src/components/Flamegraph.tsx
  app/packages/jaeger/src/components/JaegerPanel.tsx
  app/packages/jaeger/src/components/Trace.tsx
  app/packages/jaeger/src/components/Traces.tsx
Labels: changelog: added
