Repository kobsio/kobs, pull requests merged in 2023-05, with the labels that each got.

#520 [sql] Adjust SQL Plugin
  .github/workflows/continuous-integration.yaml
  app/package-lock.json
  app/packages/app/package.json
  app/packages/app/src/main.tsx
  app/packages/sql/package.json
  app/packages/sql/src/assets/icon.png
  app/packages/sql/src/components/SQLChart.tsx
  app/packages/sql/src/components/SQLChartGeneric.tsx
  app/packages/sql/src/components/SQLChartPie.tsx
  app/packages/sql/src/components/SQLChartSinglestats.tsx
  app/packages/sql/src/components/SQLPage.test.tsx
  app/packages/sql/src/components/SQLPage.tsx
  app/packages/sql/src/components/SQLPanel.test.tsx
  app/packages/sql/src/components/SQLPanel.tsx
  app/packages/sql/src/components/SQLTable.tsx
  app/packages/sql/src/index.test.ts
  app/packages/sql/src/index.ts
  app/packages/sql/src/setupTests.ts
  app/packages/sql/src/utils/clickhouse.ts
  app/packages/sql/src/utils/utils.ts
  app/packages/sql/src/vite-env.d.ts
  app/packages/sql/tsconfig.json
  app/packages/sql/tsconfig.node.json
  app/packages/sql/vite.config.ts
  cmd/kobs/main.go
  go.mod
  go.sum
  pkg/plugins/sql/instance/completions.go
  pkg/plugins/sql/instance/instance.go
  pkg/plugins/sql/instance/instance_mock.go
  pkg/plugins/sql/instance/instance_test.go
  pkg/plugins/sql/instance/querier.go
  pkg/plugins/sql/router.go
  pkg/plugins/sql/router_test.go
  pkg/plugins/sql/sql.go
  pkg/plugins/sql/sql_test.go
  pkg/utils/gnomock/clickhouse/preset.go
Labels: changelog: changed

#554 [core] Adjust Test Setup
  app/packages/core/vite.config.ts
  app/packages/flux/src/index.test.ts
  app/packages/flux/vite.config.ts
  app/packages/github/src/index.test.ts
  app/packages/github/vite.config.ts
  app/packages/grafana/src/index.test.ts
  app/packages/grafana/vite.config.ts
  app/packages/harbor/src/index.test.ts
  app/packages/harbor/vite.config.ts
  app/packages/helm/src/index.test.ts
  app/packages/helm/vite.config.ts
  app/packages/jaeger/src/index.test.ts
  app/packages/jaeger/vite.config.ts
  app/packages/jira/src/index.test.ts
  app/packages/jira/vite.config.ts
  app/packages/kiali/src/index.test.ts
  app/packages/kiali/vite.config.ts
  app/packages/klogs/src/index.test.ts
  app/packages/klogs/vite.config.ts
  app/packages/mongodb/src/index.test.ts
  app/packages/mongodb/vite.config.ts
  app/packages/opsgenie/src/index.test.ts
  app/packages/opsgenie/vite.config.ts
  app/packages/prometheus/src/index.test.ts
  app/packages/prometheus/vite.config.ts
  app/packages/rss/src/index.test.ts
  app/packages/rss/vite.config.ts
  app/packages/signalsciences/src/index.test.ts
  app/packages/signalsciences/vite.config.ts
  app/packages/sonarqube/src/index.test.ts
  app/packages/sonarqube/vite.config.ts
  app/packages/techdocs/src/index.test.ts
  app/packages/techdocs/vite.config.ts
Labels: changelog: changed

#555 [core] Change Supported Platforms for Docker Image
  .github/workflows/continuous-delivery.yaml
Labels: changelog: changed

#557 [core] Fix Topology Graph in Rows with "autoHeight"
  app/packages/core/src/components/applications/TopologyPanel.tsx
  app/packages/core/src/components/plugins/PluginPanel.tsx
Labels: changelog: fixed

#558 [core] Fix GetTopologyByIDs Function
  pkg/hub/db/db.go
Labels: changelog: fixed

#559 [jaeger] Fix Traces Panel
  app/packages/jaeger/src/components/JaegerPanel.tsx
Labels: changelog: fixed

#560 [core] Fix "interpolate" Function for Objects
  app/packages/core/src/components/dashboards/utils.ts
Labels: changelog: fixed

#561 [klogs]: parser adjustments
  pkg/plugins/klogs/instance/parser/parser.go
  pkg/plugins/klogs/instance/parser/parser_test.go
Labels: changelog: fixed

#562 [klogs]: parser - fix `_not_` with subexpression
  pkg/plugins/klogs/instance/parser/parser.go
  pkg/plugins/klogs/instance/parser/parser_test.go
Labels: changelog: fixed

#563 [prometheus] Fix yAxis min and max Setting
  app/packages/prometheus/src/components/Chart.tsx
  app/packages/prometheus/src/components/PrometheusPanel.tsx
Labels: changelog: fixed

#564 [core] Fix TeamPage
  app/packages/core/src/components/teams/TeamPage.tsx
  app/packages/core/src/components/teams/Teams.tsx
Labels: changelog: fixed

#567 [mongodb] Fix Production Build
  app/package-lock.json
  app/packages/mongodb/package.json
  app/packages/mongodb/vite.config.ts
Labels: changelog: fixed

#568 [core] Add "@codemirror/state" as External Module
  app/packages/core/vite.config.ts
  app/packages/flux/vite.config.ts
  app/packages/github/vite.config.ts
  app/packages/grafana/vite.config.ts
  app/packages/harbor/vite.config.ts
  app/packages/helm/vite.config.ts
  app/packages/jaeger/vite.config.ts
  app/packages/jira/vite.config.ts
  app/packages/kiali/vite.config.ts
  app/packages/klogs/vite.config.ts
  app/packages/mongodb/vite.config.ts
  app/packages/opsgenie/vite.config.ts
  app/packages/prometheus/vite.config.ts
  app/packages/rss/vite.config.ts
  app/packages/signalsciences/vite.config.ts
  app/packages/sonarqube/vite.config.ts
  app/packages/sql/vite.config.ts
  app/packages/techdocs/vite.config.ts
Labels: changelog: fixed

#569 [core] Fix Save Function when Save is Disabled
  app/packages/core/src/components/edit/EditPage.tsx
Labels: changelog: fixed

#570 [sql] Add CSV Export
  app/packages/sql/src/components/SQLPage.tsx
  app/packages/sql/src/components/SQLPanel.tsx
  app/packages/sql/src/components/SQLTable.tsx
Labels: changelog: added

#571 [core] Fix Lists across all Plugins
  app/packages/core/src/components/applications/ApplicationGroupsPanel.tsx
  app/packages/core/src/components/applications/ApplicationsPage.tsx
  app/packages/core/src/components/applications/ApplicationsPanel.tsx
  app/packages/core/src/components/dashboards/DashboardsPanel.tsx
  app/packages/core/src/components/teams/Teams.tsx
  app/packages/grafana/src/components/GrafanaPage.tsx
  app/packages/grafana/src/components/GrafanaPanel.tsx
  app/packages/harbor/src/components/Artifacts.tsx
  app/packages/harbor/src/components/Projects.tsx
  app/packages/harbor/src/components/Repositories.tsx
  app/packages/jaeger/src/components/Trace.tsx
  app/packages/jaeger/src/components/Traces.tsx
  app/packages/jira/src/components/Issues.tsx
  app/packages/opsgenie/src/components/Alerts.tsx
  app/packages/opsgenie/src/components/Incidents.tsx
  app/packages/rss/src/components/Feed.tsx
  app/packages/techdocs/src/components/Services.tsx
Labels: changelog: fixed

#572 [sql]: Fix `type: singlestats`
  app/packages/sql/src/components/SQLChart.tsx
  app/packages/sql/src/components/SQLPanel.test.tsx
Labels: changelog: fixed

#576 [core] Fix Dashboard Updates for Back Button
  app/packages/core/src/components/applications/TopologyPage.tsx
  app/packages/core/src/components/applications/TopologyPanel.tsx
  app/packages/core/src/components/dashboards/Dashboards.tsx
Labels: changelog: fixed
